### ISSUE TITLE
Authentication: Server error 500 on create new account

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#105]
On creating new account, user receives a server error.  It appears that the account creation goes through, however.  

(Also, the button "Log in" is misleading.)

Recommended changes:  
1) Log in -> Create Account
2) Instead of the 500 error screen, a screen that says once you attempt to log in, you will get a verification email to your email account 
2a) OR - better - send the email immediately on choosing to create the account, so that the extra step of a failed attempt to log in is not neccessary.

**Comment by zachmccormick** [comment]
This was due to Postgres's sequence values being messed up in the database.  I fixed the Sign In -> Create Account text issue in 1107c36bde3e887386561fbcded6d44507dfd7c2, as well as added a Log Out button to the navbar.
