### ISSUE TITLE
Setup Screen: Sometimes the Select2 widget doesn't load correctly

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#106]
It can happen that the Setup screen shows up with different styling for the Grouping and Tags sections.  This is remedied mostly by refreshing the page or, in the case of Groupings, by re-selecting a grouping.

First, improper styling (on computer)
<img width="800" alt="screen shot 2018-08-14 at 10 25 30 am" src="https://user-images.githubusercontent.com/769072/44101302-befcb6c0-9fac-11e8-8999-ed4229e114d1.png">

Next, fixing most by refreshing the page
<img width="839" alt="screen shot 2018-08-14 at 10 25 47 am" src="https://user-images.githubusercontent.com/769072/44101334-d402d360-9fac-11e8-97ea-d82c2a3e1e06.png">

Finally, fixing the rest by twiddling the Grouping (this last one actually isn't a 'fix' from the prior one (it's just that Individuals grouping can't be edited).  But twiddling the grouping does often take one from step 1 to step 3).
<img width="771" alt="screen shot 2018-08-14 at 10 25 53 am" src="https://user-images.githubusercontent.com/769072/44101357-e0c336a8-9fac-11e8-88a4-563408679b46.png">

**Comment by zachmccormick** [comment]
I've noticed that too and not sure exactly why that is...
