### ISSUE TITLE
Course Import: Add error messages to this page

### ISSUE THREAD

**Issue by zachmccormick** [TrailblazingTech/LSOA#109]
[LSOA Class Roster 20180814.xlsx](https://github.com/TrailblazingTech/LSOA/files/2302229/LSOA.Class.Roster.20180814.xlsx)

This file caused Corey to experience an error, but the error message was not shown. Either this file shouldn't create an error or at a minimum, the error message should be shown!

**Comment by cbradyatinquire** [comment]
This file appears to me to be correctly formatted, and it was created from the provided template.  It creates a preview that looks good.  But on import, it creates an error message without details or information that would guide changes to the roster data.

**Comment by cbradyatinquire** [comment]
Import is complete - we'll be able to test this again on Wednesday 9/19 with our other teachers.

**Comment by cbradyatinquire** [comment]
works

**Comment by cbradyatinquire** [comment]
Closing
