### ISSUE TITLE
Context Tags: "null" owner column should indicate that the tag is visible for everyone

### ISSUE THREAD

**Issue by zachmccormick** [TrailblazingTech/LSOA#110]
We want to support the concept of "shared" context tags (right now, they are owned by an individual user). We should be able to do this by making the "owner_id" column allow NULL, then make it so that NULL means that it is able to be chosen by anybody/everybody.

**Comment by zachmccormick** [comment]
Finished with 4f5534da04bcdab96bc0bcd87fa994f9b6ec08d8.

@cbradyatinquire if you use the administrator interface, you can set the owner of a tag (or create a new one) as "None", which will make it public (i.e. it will show up for everyone). If you create a new tag from the Setup screen, it will belong to/only show up for you unless you change that in the admin interface.

**Comment by cbradyatinquire** [comment]
New issue opened due to bug in this story -> right now, a tag entered this way DOES show up nicely in the Setup screen.  BUT it gets "munged" in the Observation screen (replaced by a NUMBER) - and that number then starts showing up in the tag list.

**Comment by zachmccormick** [comment]
I think this got fixed when I deployed all of the latest code and confirmed that it worked.

In the development version, all of the colors are set to #000000 which is black, which makes them just look like black boxes on the screen. I'm going to change the default color to something more reasonable (maybe a green or light blue) and try to fix the color picker on the tags screen.

Can you confirm the issue you saw was fixed?

**Comment by cbradyatinquire** [comment]
WOrks.  Closing.
