### ISSUE TITLE
Error at Login

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#124]
I sometimes (both on dev and production) have gotten an error on attempting to log in.  Image of error screen captured below.  From this state, if I hit the back button, I find I am logged in.

<img width="519" alt="screen shot 2018-09-04 at 8 11 46 am" src="https://user-images.githubusercontent.com/769072/45033526-6da57b80-b01a-11e8-9538-f9dbf546c908.png">

**Comment by cbradyatinquire** [comment]
I am unsure about the severity of this issue - it COULD be a result of interactions between my computer's password manager (which aggressively tries to log me in sometimes) and the system.  If other people DON'T see this ever or often, it is low priority.

**Comment by zachmccormick** [comment]
@cbradyatinquire have you seen this error anymore or has anyone else reported this? If not I'm going to close it

**Comment by cbradyatinquire** [comment]
I have seen it but not super recently -> when it happens, refreshing the page 'fixes' it -C

Corey Brady, Ph.D.
Assistant Professor, Learning Sciences
Department of Teaching & Learning
Peabody College
Vanderbilt University

**Comment by zachmccormick** [comment]
Great! I'm going to close this then
