### ISSUE TITLE
Plan for future (next year, perhaps) to handle rosters that may/will involve existing students

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#143]
Addressing the question:
How can we create rosters NEXT YEAR, in an efficient, automated way that also connects the students with their identities from this year?

**Comment by zachmccormick** [comment]
Will students ever be in more than one class? If not, we can make the roster upload form automatically take care of that. If the students match (via external ID and/or first name-last name), then we can remove them from the class they're currently in, and place them in a new class based on the most recently uploaded roster

**Comment by cbradyatinquire** [comment]
I think that this is almost a completely valid assumption.  MOREOVER, I would be completely comfortable with it if we are able to manually add them to a second class after roster-upload, if there are crazy edge cases.

The only thing I'm worried about is, we DO want to be able to do database queries about PAST YEARS - so, a student who is in Course A and has observations about them, needs to be able to "graduate" to Course B without our losing the ability to see those observations in the context of Course A, when the dates are appropriate...  Does that make sense?
