### ISSUE TITLE
"Slow Loading" issue

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#144]
In server reports it has been noted that some pages have taken a long time to load.  Proposed measures to address include software optimizations and hardware (server) upgrades.  

As an example on the software front, the Star Charts load (I believe) with the Universe of students selected/displayed.  If they default to the teacher's default class (or to the FIRST class if no default is set), that could make a very large difference

**Comment by zachmccormick** [comment]
I upgraded both the database and the application server from "hobby level" to "production level". This should help alleviate hardware related things.

Next step here is to add `django-debug-toolbar` to develop (and generate approximately the same amount of test data for the development environment) and see what pages are slow + fix the issues. I know Star Chart in particular should be changed.

**Comment by cbradyatinquire** [comment]
Cool - star chart could be addressed in part by defaulting to the user's currently-selected class (or to default if no selected class), which (I think?) would reduce the number of queries that are needed to create the initial view. ?

**Comment by zachmccormick** [comment]
Closing this since it seems WAY faster now finally!
