### ISSUE TITLE
New "report" / "star chart"

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#155]
New report to show teachers' use of construct sublevels.  See mockup in image.
<img width="739" alt="screen shot 2018-10-03 at 10 55 36 pm" src="https://user-images.githubusercontent.com/769072/46452174-e73aa180-c75f-11e8-9067-fa27fa2f953d.png">

Observations in this view should be circles like in Star Chart 2 but a touch smaller. 

Clicking on them should bring up the observation summary window like in other star charts.  Link should open dialog with new "read only observation view" in issue #154

**Comment by zachmccormick** [comment]
I think this is pretty straightforward
