### ISSUE TITLE
Possibly BIG story:  Researcher View

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#158]
This story relates to the fact that the App is a teaching tool used by the teacher community for their own purposes AND a tool for researchers to contribute to that community's conversation.

We've discussed a sequence of things based on this...
A. Provide some way to for us to identify which students have NOT consented to have their data used for research.
B. Add identifier to users who are researchers.
C. For users who are researchers, display students who are not consented with an annotation (like * or whatever)
D. IDEALLY, (ok if later) for users who are researchers, suppress links to observations of students who are not consented.

**Comment by zachmccormick** [comment]
OK I think this is doable:

A. this is easy via a boolean (true/false) column on the students table. Is this something people would want to import via CSV or something they could do from the administrator view?

B. this is also easy via a new group that users can be assigned to (currently there are "teachers" and "administrators")

C. this should be pretty easy to do all over the UI (I can say like `if !student.consented and user.is_researcher then student.name = student.name + '*'`)

D. similarly easy to C.

Are there functionalities of the site that researchers should not be able to use?

**Comment by zachmccormick** [comment]
https://www.dropbox.com/s/cytcsuzdcrrs4oa/Screenshot%202019-03-02%2013.39.38.png?dl=0

This is done except for D.

What do we do about an observation that has a mix of non-consent and consent students?

**Comment by cbradyatinquire** [comment]
Zach

That is a great question.  Let me pass it around to the PIs (copied here)

I think that we have to limit or prevent our viewing such an observation: let me confirm.

Rich, Leona – the question is, if there is an observation with a photo or video clip that contains non-consented students as well as consented students, does it show up in the Researcher view?  That is, does it show as an observation for the consented students?   If so, can we give Zach guidelines for what to show?

-C


Corey Brady, Ph.D.
Assistant Professor, Learning Sciences
Department of Teaching & Learning
Peabody College
Vanderbilt University

**Comment by zachmccormick** [comment]
This is now live (aside from the fact that currently you can view observations that include a mix). I need to add a button or something to toggle people into the Researcher role in the Users page. Right now I can do it manually though in the database

**Comment by cbradyatinquire** [comment]
Cool – if you tell me two accounts – one that is researcher one that is not (and login info, I can test and then demo).  Thanks!
-c

PS:  are the other Star Chart stories also proceeding well?  (If any blocks, let me know if I can help)  Best C

Corey Brady, Ph.D.
Assistant Professor, Learning Sciences
Department of Teaching & Learning
Peabody College
Vanderbilt University
