### ISSUE TITLE
Maintain state in the latest un-saved observation

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#164]
Right now, if you begin an observation, leave the screen, and come back, your work is cleared.  This is USUALLY only an inconvenience.  

However, there is at least one place where it puts the teachers in a bind.  If they are working with the class, realize that the data they've collected falls outside of the set of the constructs you have chosen, and then need to go back to the SETUP screen, you lose your work when you return.  

Saving the in-process state of the observation screen would solve this problem.  An alternative solution could be to figure out a later editing path using the "N/A" observation classification mentioned in #163

**Comment by zachmccormick** [comment]
closing this and copying the description to #145 since it's essentially the same thing. See my discussion there for more details.
