### ISSUE TITLE
New form of Context Tag

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#166]
We need a context tag that allows the teacher to describe the CURRICULAR FOCUS of the lesson from which the observation is taken. 

The team's proposal is the following...
1) On the SETUP screen, this is a context tag. ("Curricular Focus").
2) (Still on the SETUP screen) when the user selects it, they are given a dialog to write a phrase or sentence describing the curricular focus.
3) On the Observation screen, it shows up as selected by default, as all Context Tags do. 
4) When the user clicks it, they are given a dialog to CHANGE the description.
5) The focus can't be turned "off" like other context tags can.

So, it's a context tag with unique behavior.

**Comment by zachmccormick** [comment]
This is pretty straightforward!
