### ISSUE TITLE
Add a "date" field (use datepicker) to the UI, autofilled with today

### ISSUE THREAD

**Issue by zachmccormick** [TrailblazingTech/LSOA#17]
"Date.  This should probably be up on the front screen rather than in the observation app. It could default to the current date, but it should be editable (as people will, we think, take pictures from their phone of physical artifacts that might have been from a while ago)."

**Comment by zachmccormick** [comment]
@cbradyatinquire is this so that someone can set the date to yesterday then take pictures of projects that students turned in and annotate them, or a similar behavior? Just making sure I understand what the goal is

**Comment by cbradyatinquire** [comment]
RE: needs discussion - this is for two reasons.  (1) so that we have a date associated with all observations, and (2) so that the interface allows us to make that date NOT the current date (e.g., if teacher is taking pictures today of work submitted last week by students).
