### ISSUE TITLE
Bug: Return to setup screen after making new grouping

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#177]
After leaving the setup screen to create a new grouping, the app returns to the setup screen in its default state, cleared of choices made by the user before creating the new grouping.  It would be great to come back to the class we'd just added the grouping to, and to the other state of dropdowns, inputs, and checkboxes as well.

**Comment by zachmccormick** [comment]
I don't think this should be too hard.

Note to myself or other implementor: let's just save the state of this form in the user's session and restore it (if they go to any screen like that - tag editing, group editing, etc.) Maybe make it have a TTL/timeout of like 30 minutes or something and if it's older than that, just start fresh
