### ISSUE TITLE
Bug with date of observation (now know how to reproduce it).

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#179]
There is a problem with the date of observation: in a teacher meeting **on 11/5**, it defaulted to a time set some 50-60 years in the future.  
CB: I am unable to reproduce this on a computer -> will try with ipad.

**Comment by cbradyatinquire** [comment]
I discovered how to reproduce this - it occurs when you click on the CALENDAR picker to CHANGE the date...

<img width="307" alt="screen shot 2018-12-02 at 10 39 50 pm" src="https://user-images.githubusercontent.com/769072/49353451-5dd21d80-f683-11e8-9bb9-9098094ba812.png">

**Comment by zachmccormick** [comment]
It's probably some minor bug where we're doing something wrong with numbers (milliseconds to seconds or something like that). Will investigate

**Comment by cbradyatinquire** [comment]
(This happens to hit the teachers in a common workflow where they need to change the date of the observation - just a bump up in importance)
