### ISSUE TITLE
Correction to #178:  Simply want to remove the "DANGER" symbol for group-size numbers that will leave remainders.

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#182]
In #178 we thought teachers wanted the auto-group to distribute any remainder-students.  BUT it turns out, on having asked them again, that they really only wanted us to REMOVE the warning icon that shows up when the group  size doesn't divide the number of students.   They are fine with needing to manually distribute the remainder students.  It's just that SOME of the teachers thought that the icon meant they were not permitted to use those group sizes at all (!)

**Comment by zachmccormick** [comment]
Awesome this is easy
