### ISSUE TITLE
Make the "add a tag" functionality into a separate screen similar to "Create New Grouping"

### ISSUE THREAD

**Issue by zachmccormick** [TrailblazingTech/LSOA#24]
"Data Marking wise, it is ideal for this to be a pretty CONTROLLED VOCABULARY – the team was thinking, for this reason, that it might be better to make adding a tag a bit harder to do (like adding a grouping maybe).  So that on the main screen you're just choosing between existing tags or choosing to go to a screen where tag-invention can happen."

Maybe like GitHub labels? You can assign labels to issues but to manage your labels you go to a separate screen (and there you get to color code them, which could be a cool easy feature to add as well?)

**Comment by cbradyatinquire** [comment]
I think that this works really well.  Color coding is a great idea, and community tagging is fantastic.  This suggests that we might need the tags to be editable by a user or group (and the edits scoped to that group).  Does that make sense?  It's fine to defer this to mid summer when we have a workshop with the teachers, where this use might start to come into focus

**Comment by zachmccormick** [comment]
Great! Moving this to low priority right now then!
