### ISSUE TITLE
Edit Last Observation

### ISSUE THREAD

**Issue by zachmccormick** [TrailblazingTech/LSOA#28]
"Edit last observation. - this doesn't work in the current app – I told them it was a placeholder for a future edit-observation screen.  This is where the TITLE thing came up – maybe it's most common that people add that there.  And maybe that screen should also be where we go from the Star Chart when you select an observation."

**Comment by zachmccormick** [comment]
Now that the observation screen uses bootstrap it shouldn't be too hard to be able to edit an observation by rendering it with a pre-filled form. Some of the more custom UI elements might need some tweaking to render correctly though.

**Comment by julierae** [comment]
[This Pull Request](https://github.com/TrailblazingTech/LSOA/pull/77) implements everything except existing files.  Need more information about how they need to be interacted with.  Viewing video and add/replacing/removing videos are maybe best as discrete actions... 

Not closing issue yet.
