### ISSUE TITLE
Dot Plot: Viewing past observations

### ISSUE THREAD

**Issue by zachmccormick** [TrailblazingTech/LSOA#29]
" A BIG AREA of work – viewing and visualizing existing observations in different filters/configurations, etc.  I think the group got a clear sense that flexibly visualizing and analyzing the set of collected observations was where a huge amount of the payoff was. (Hooray!)  So this is a giant area for specifications & envisioning screens"
~I think we should figure out what this means via a discussion first, then prototype a couple ways to look at them~

See Corey's comment below on the "dot plot". I imagine that this will be similar to the star chart today, where you can select a start date/end date and a course from dropdowns at the top, which cause the page to reload and the graph to re-render.

**Comment by cbradyatinquire** [comment]
Right - this "epic" signals a collection of stories for Views like the Star Chart.  I believe the group is convinced that having several/many views of history for analysis & assessment is a good thing.  That allows us to design for particular tasks, and MAYBE later combine ones that seem to work with the same or similar views.

**Comment by zachmccormick** [comment]
Once we finish with this iteration of the high priority items and the next time there's a workshop with the teachers, could y'all do an exercise in drawing out on paper/on a whiteboard what you imagine might be useful ways to slice + dice the data or view the individual/aggregate observations? I think that a sort of "design session" is needed to figure out a few prototypes we can make of this screen.

**Comment by cbradyatinquire** [comment]
Exercise on paper sounds like a GREAT idea.  
Even before this, though, we do know that we want a kind of "dot plot" view as in the powerpoint sketch (attached).  Here, the date is selected, and we get one "dot" for each observation, which each would have the modal dialog to preview & then possibly edit the observation, like in the Star Chart.
<img width="431" alt="screen shot 2018-07-22 at 4 42 08 pm" src="https://user-images.githubusercontent.com/769072/43050437-5d4a7d94-8dce-11e8-8c0f-aa4369df6d61.png">
