### ISSUE TITLE
Video Note size problem

### ISSUE THREAD

**Issue by zachmccormick** [TrailblazingTech/LSOA#40]
"Enhancement:  RE: video notes - When a video note is added, it displaces the construct definition listing (shoving it off the screen to the bottom).  I would prefer it if the text notes area became smaller to compensate for the video's size. That area already scrolls nicely, so it would work, i think."

I think this also was a WebRTC-era bug and can be closed, but adding here for tracking just in case.

**Comment by zachmccormick** [comment]
@cbradyatinquire is this still an issue now on https://lsoa-dev.trailblazingtech.com/ ? Again - can definitely fix if it is - just trying to get rid of any old issues on here.

**Comment by cbradyatinquire** [comment]
I believe this is now working
