### ISSUE TITLE
Add some space between construct selection row and capture image/video row

### ISSUE THREAD

**Issue by zachmccormick** [TrailblazingTech/LSOA#43]
"BUG/ADJUSTMENT REQUEST.  For UI/UX, it's probably better to have a bit more space between the construct selection buttons and the video capture button row.  They are immediately on top of each other now."

**Comment by zachmccormick** [comment]
@cbradyatinquire is this ticket still valid for https://lsoa-dev.trailblazingtech.com/ ? I can add more space, but this request may have been from a previous version of the app

**Comment by cbradyatinquire** [comment]
I think that this is resolved with the bootstrap shift.
