### ISSUE TITLE
filter the ~150 students down to the members of the active class (or, to classes that are "owned" by the current user who is currently logged in

### ISSUE THREAD

**Issue by zachmccormick** [TrailblazingTech/LSOA#68]

**Comment by cbradyatinquire** [comment]
This is for the Star Chart.  Star chart should show the currently-being-observed class.  
(Or, if it's accessed from the front screen, it should require the user to select a class.

**Comment by zachmccormick** [comment]
Done! It shows all students by default at first but the dropdown at the top should let you pick a particular class
