### ISSUE TITLE
Ability to return to the setup screen to add or subtract construct levels or otherwise EDIT the setup

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#69]

**Comment by zachmccormick** [comment]
I added a back button, but currently it will lose your pre-selected construct sublevels. I will try to get this fixed in the next release

**Comment by zachmccormick** [comment]
@cbradyatinquire this should actually be fixed on lsoa-dev.trailblazingtech.com when it redeploys next! Let me know if that's not the case. You might need to do a hard refresh (usually shift-command-R in chrome on mac) to get it to load all of the scripts again.
