### ISSUE TITLE
Auto-generate groupings by randomly assigning students to groups of a given size

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#70]
The UI should allow creating groups of size 2, 3, 4, 5 (that's probably enough).  Roster is then divided randomly into groups of this size, with extras creating groups of size 1 more.  Then the grouping should be manually editable with the same interface that the current all-manual grouping maker uses.

**Comment by zachmccormick** [comment]
@cbradyatinquire I think you can do this from the group editor? I do understand that, at the moment, you can't go back and edit groups once they're already made though. I'll rename the ticket to reflect that need unless you meant something else from this.

**Comment by cbradyatinquire** [comment]
@zachmccormick The "random" function is the key.  We want the teacher to be able to press a button and sort their class roster into a GROUPING that involves, e.g.,  "groups of 3." They will need to do that for the research design (so that we're able to distinguish what individuals can do, since they're with different kids at different times.  Then, the EDITING is also important, because teachers know that some kids just cannot be put together.  This editing can happen right away (right after the randomizer sets groups of a chosen size) and in a later edit-the-grouping session.

**Comment by zachmccormick** [comment]
I'm not sure I understand it. I took a short video of this functionality of what I understand to be "random groups of 3" or "random groups of 2": https://www.youtube.com/watch?v=3v_G7a5I6jw

You can also drag and drop individual names from the different columns before or after selecting a random group. Let me know what is needed _beyond_ what is possible in this interface.
