### ISSUE TITLE
Observation Screen: When taking a new observation (after the time limit on "View Past Observation" has expired) there is a useless "New Observation" button on the bottom right

### ISSUE THREAD

**Issue by zachmccormick** [TrailblazingTech/LSOA#83]
https://www.dropbox.com/s/b2umkjj5gwdc2u8/Screenshot%202018-07-30%2009.11.31.png?dl=0

After you take a first observation, this button changes to "View Last Observation" which makes sense.

**Comment by cbradyatinquire** [comment]
(it's at the bottom LEFT)
