### ISSUE TITLE
Setup Screen: Teacher accounts should bring up a default class 

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#90]
We would like a teacher to be associated with a Course/class, as their 'primary' connection.  It is great (and important) that a teacher can do observations for any class, but we also want the list to come up with their main class selected.  This, i imagine, involves being able to create /edit that association separately, since teachers may be created before or after Courses.

**Comment by zachmccormick** [comment]
Maybe we can add a link, similar to the "Add New Grouping" link, so that in the Setup screen, when you select a course, you can "Set as default course"?
